package org.wtmp.darktimes.repository;

import org.springframework.stereotype.Component;
import org.wtmp.darktimes.game.Icon;

import java.util.HashSet;
import java.util.Set;

@Component
public class IconRepository {
    private Set<Icon> iconSet = new HashSet<>();

    public Set<Icon> findAll() {
        return iconSet;
    }

    public Icon findByCode(int code) {
        return iconSet.stream().filter(i -> i.getCode() == code)
                .findFirst().orElse(null);
    }

    public IconRepository() {
        iconSet.add(Icon
                .builder()
                //🌳
                .code(1)
                .name("simple tree")
                .symbol("\uD83C\uDF33")
                .build());
        iconSet.add(Icon
                .builder()
                //🌲
                .code(2)
                .name("fir-tree")
                .symbol("\uD83C\uDF32")
                .build());
        iconSet.add(Icon
                .builder()
                //🌴
                .code(3)
                .name("palm tree")
                .symbol("\uD83C\uDF34")
                .build());
        iconSet.add(Icon
                .builder()
                //🌵
                .code(4)
                .name("cactus")
                .symbol("\uD83C\uDF35")
                .build());
        iconSet.add(Icon
                .builder()
                //🌱
                .code(5)
                .name("grass")
                .symbol("\uD83C\uDF31")
                .build());
        iconSet.add(Icon
                .builder()
                //🌾
                .code(6)
                .name("flower")
                .symbol("\uD83C\uDF3E")
                .build());
        iconSet.add(Icon
                .builder()
                //🍀
                .code(7)
                .name("clover")
                .symbol("\uD83C\uDF40")
                .build());
        iconSet.add(Icon
                .builder()
                //🍄
                .code(8)
                .name("mushroom")
                .symbol("\uD83C\uDF44")
                .build());
        iconSet.add(Icon
                .builder()
                //☘
                .code(9)
                .name("clover-3")
                .symbol("☘")
                .build());
        iconSet.add(Icon
                .builder()
                //🏔
                .code(10)
                .name("snow-capped mountain")
                .symbol("\uD83C\uDFD4")
                .build());
        iconSet.add(Icon
                .builder()
                //⛰
                .code(11)
                .name("mountain")
                .symbol("⛰")
                .build());
        iconSet.add(Icon
                .builder()
                //🗻
                .code(12)
                .name("mountain fuji")
                .symbol("\uD83D\uDDFB")
                .build());
        iconSet.add(Icon
                .builder()
                //🏕
                .code(13)
                .name("camping")
                .symbol("\uD83C\uDFD5")
                .build());
        iconSet.add(Icon
                .builder()
                //🏜
                .code(14)
                .name("desert")
                .symbol("\uD83C\uDFDC")
                .build());
        iconSet.add(Icon
                .builder()
                //🏝
                .code(15)
                .name("desert island")
                .symbol("\uD83C\uDFDD")
                .build());
        iconSet.add(Icon
                .builder()
                //🏛
                .code(16)
                .name("building")
                .symbol("\uD83C\uDFDB")
                .build());
        iconSet.add(Icon
                .builder()
                //🪨
                .code(17)
                .name("rock")
                .symbol("\uD83E\uDEA8")
                .build());
        iconSet.add(Icon
                .builder()
                //🪵
                .code(18)
                .name("wood")
                .symbol("\uD83E\uDEB5")
                .build());
        iconSet.add(Icon
                .builder()
                //🛖
                .code(19)
                .name("hut")
                .symbol("\uD83D\uDED6")
                .build());
        iconSet.add(Icon
                .builder()
                //🏚
                .code(20)
                .name("derelict house")
                .symbol("\uD83C\uDFDA")
                .build());
        iconSet.add(Icon
                .builder()
                //🏠
                .code(21)
                .name("house")
                .symbol("\uD83C\uDFE0")
                .build());
        iconSet.add(Icon
                .builder()
                //🏦
                .code(22)
                .name("bank")
                .symbol("\uD83C\uDFE6")
                .build());
        iconSet.add(Icon
                .builder()
                //🏰
                .code(23)
                .name("castle")
                .symbol("\uD83C\uDFF0")
                .build());
        iconSet.add(Icon
                .builder()
                //⛪
                .code(24)
                .name("church")
                .symbol("⛪")
                .build());
        iconSet.add(Icon
                .builder()
                //🕌
                .code(25)
                .name("mosque")
                .symbol("\uD83D\uDD4C")
                .build());
        iconSet.add(Icon
                .builder()
                //🕍
                .code(26)
                .name("synagogue")
                .symbol("\uD83D\uDD4D")
                .build());
        iconSet.add(Icon
                .builder()
                //⛺
                .code(27)
                .name("tent")
                .symbol("⛺")
                .build());
        iconSet.add(Icon
                .builder()
                //🎪
                .code(28)
                .name("circus tent")
                .symbol("\uD83C\uDFAA")
                .build());
        iconSet.add(Icon
                .builder()
                //⛵
                .code(29)
                .name("sailboard")
                .symbol("⛵")
                .build());
        iconSet.add(Icon
                .builder()
                //🛶
                .code(30)
                .name("canoe")
                .symbol("\uD83D\uDEF6")
                .build());
        iconSet.add(Icon
                .builder()
                //❄
                .code(31)
                .name("snowflake")
                .symbol("❄")
                .build());
        iconSet.add(Icon
                .builder()
                //🔥
                .code(32)
                .name("fire")
                .symbol("\uD83D\uDD25")
                .build());
        iconSet.add(Icon
                .builder()
                //💧
                .code(33)
                .name("droplet")
                .symbol("\uD83D\uDCA7")
                .build());
        iconSet.add(Icon
                .builder()
                //🌊
                .code(34)
                .name("water wave")
                .symbol("\uD83C\uDF0A")
                .build());
        iconSet.add(Icon
                .builder()
                //🕯
                .code(35)
                .name("candle")
                .symbol("\uD83D\uDD6F")
                .build());
        iconSet.add(Icon
                .builder()
                //📜
                .code(36)
                .name("scroll")
                .symbol("\uD83D\uDCDC")
                .build());
        iconSet.add(Icon
                .builder()
                //💰
                .code(37)
                .name("money bag")
                .symbol("\uD83D\uDCB0")
                .build());
        iconSet.add(Icon
                .builder()
                //🪜
                .code(38)
                .name("ladder")
                .symbol("\uD83E\uDE9C")
                .build());
        iconSet.add(Icon
                .builder()
                //🩸
                .code(39)
                .name("drop of blood")
                .symbol("\uD83E\uDE78")
                .build());
        iconSet.add(Icon
                .builder()
                //🚪
                .code(40)
                .name("door")
                .symbol("\uD83D\uDEAA")
                .build());
        iconSet.add(Icon
                .builder()
                //⚰
                .code(41)
                .name("coffin")
                .symbol("⚰")
                .build());
        iconSet.add(Icon
                .builder()
                //🪦
                .code(42)
                .name("headstone")
                .symbol("\uD83E\uDEA6")
                .build());
        iconSet.add(Icon
                .builder()
                //🪧
                .code(43)
                .name("placard")
                .symbol("\uD83E\uDEA7")
                .build());
        iconSet.add(Icon
                .builder()
                //
                .code(44)
                .name("money bag")
                .symbol("\uD83D\uDCB0")
                .build());
        iconSet.add(Icon
                .builder()
                //🗿
                .code(45)
                .name("moai")
                .symbol("\uD83D\uDDFF")
                .build());
        iconSet.add(Icon
                .builder()
                //🧿
                .code(46)
                .name("portal")
                .symbol("\uD83E\uDDFF")
                .build());
        iconSet.add(Icon
                .builder()
                //⬛
                .code(47)
                .name("black square")
                .symbol("⬛")
                .build());
        iconSet.add(Icon
                .builder()
                //🟧
                .code(48)
                .name("orange square")
                .symbol("\uD83D\uDFE7")
                .build());
        iconSet.add(Icon
                .builder()
                //🟨
                .code(49)
                .name("yellow square")
                .symbol("\uD83D\uDFE8")
                .build());
        iconSet.add(Icon
                .builder()
                //🟦
                .code(50)
                .name("blue square")
                .symbol("\uD83D\uDFE6")
                .build());
        iconSet.add(Icon
                .builder()
                //🟫
                .code(51)
                .name("brown square")
                .symbol("\uD83D\uDFEB")
                .build());
        iconSet.add(Icon
                .builder()
                //⬜
                .code(52)
                .name("white square")
                .symbol("⬜")
                .build());
        iconSet.add(Icon
                .builder()
                //🟩
                .code(53)
                .name("green square")
                .symbol("\uD83D\uDFE9")
                .build());
        iconSet.add(Icon
                .builder()
                //🚩
                .code(54)
                .name("flag")
                .symbol("\uD83D\uDEA9")
                .build());
        iconSet.add(Icon
                .builder()
                //☠
                .code(55)
                .name("pirate flag")
                .symbol("☠")
                .build());
        iconSet.add(Icon
                .builder()
                //😈
                .code(56)
                .name("smiling face with horns")
                .symbol("\uD83D\uDE08")
                .build());
        iconSet.add(Icon
                .builder()
                //💀
                .code(57)
                .name("skull")
                .symbol("\uD83D\uDC80")
                .build());
        iconSet.add(Icon
                .builder()
                //☠
                .code(58)
                .name("skull and crossbones")
                .symbol("☠")
                .build());
        iconSet.add(Icon
                .builder()
                //🤡
                .code(59)
                .name("clown face")
                .symbol("\uD83E\uDD21")
                .build());
        iconSet.add(Icon
                .builder()
                //👹
                .code(60)
                .name("ogre")
                .symbol("\uD83D\uDC79")
                .build());
        iconSet.add(Icon
                .builder()
                //👺
                .code(61)
                .name("goblin")
                .symbol("\uD83D\uDC7A")
                .build());
        iconSet.add(Icon
                .builder()
                //👻
                .code(62)
                .name("ghost")
                .symbol("\uD83D\uDC7B")
                .build());
        iconSet.add(Icon
                .builder()
                //👽
                .code(63)
                .name("alien")
                .symbol("\uD83D\uDC7D")
                .build());
        iconSet.add(Icon
                .builder()
                //💬
                .code(64)
                .name("speech balloon")
                .symbol("\uD83D\uDCAC")
                .build());
        iconSet.add(Icon
                .builder()
                //💤
                .code(65)
                .name("zzz")
                .symbol("\uD83D\uDCA4")
                .build());
        iconSet.add(Icon
                .builder()
                //🫀
                .code(66)
                .name("heart")
                .symbol("\uD83E\uDEC0")
                .build());
        iconSet.add(Icon
                .builder()
                //🧔
                .code(67)
                .name("person beard")
                .symbol("\uD83E\uDDD4")
                .build());
        iconSet.add(Icon
                .builder()
                //👧
                .code(68)
                .name("girl")
                .symbol("\uD83D\uDC67")
                .build());
        iconSet.add(Icon
                .builder()
                //💂
                .code(69)
                .name("guard")
                .symbol("\uD83D\uDC82")
                .build());
        iconSet.add(Icon
                .builder()
                //🥷
                .code(70)
                .name("ninja")
                .symbol("\uD83E\uDD77")
                .build());
        iconSet.add(Icon
                .builder()
                //🫅
                .code(71)
                .name("king")
                .symbol("\uD83E\uDEC5")
                .build());
        iconSet.add(Icon
                .builder()
                //🧛
                .code(72)
                .name("vampire")
                .symbol("\uD83E\uDDDB")
                .build());
        iconSet.add(Icon
                .builder()
                //🧟
                .code(73)
                .name("zombie")
                .symbol("\uD83E\uDDDF")
                .build());
        iconSet.add(Icon
                .builder()
                //🧌
                .code(74)
                .name("troll")
                .symbol("\uD83E\uDDCC")
                .build());
        iconSet.add(Icon
                .builder()
                //🐒
                .code(75)
                .name("monkey")
                .symbol("\uD83D\uDC12")
                .build());
        iconSet.add(Icon
                .builder()
                //🐕
                .code(76)
                .name("dog")
                .symbol("\uD83D\uDC15")
                .build());
        iconSet.add(Icon
                .builder()
                //🐈
                .code(77)
                .name("cat")
                .symbol("\uD83D\uDC08")
                .build());
        iconSet.add(Icon
                .builder()
                //🐅
                .code(78)
                .name("tiger")
                .symbol("\uD83D\uDC05")
                .build());
        iconSet.add(Icon
                .builder()
                //🐆
                .code(79)
                .name("leopard")
                .symbol("\uD83D\uDC06")
                .build());
        iconSet.add(Icon
                .builder()
                //🫏
                .code(80)
                .name("donkey")
                .symbol("\uD83E\uDECF")
                .build());
        iconSet.add(Icon
                .builder()
                //🐎
                .code(81)
                .name("horse")
                .symbol("\uD83D\uDC0E")
                .build());
        iconSet.add(Icon
                .builder()
                //🦬
                .code(82)
                .name("bison")
                .symbol("\uD83E\uDDAC")
                .build());
        iconSet.add(Icon
                .builder()
                //🐖
                .code(83)
                .name("pig")
                .symbol("\uD83D\uDC16")
                .build());
        iconSet.add(Icon
                .builder()
                //🐏
                .code(84)
                .name("ram")
                .symbol("\uD83D\uDC0F")
                .build());
        iconSet.add(Icon
                .builder()
                //🐐
                .code(85)
                .name("goat")
                .symbol("\uD83D\uDC10")
                .build());
        iconSet.add(Icon
                .builder()
                //🐁
                .code(86)
                .name("mouse")
                .symbol("\uD83D\uDC01")
                .build());
        iconSet.add(Icon
                .builder()
                //🐀
                .code(87)
                .name("rat")
                .symbol("\uD83D\uDC00")
                .build());
        iconSet.add(Icon
                .builder()
                //🐇
                .code(88)
                .name("rabbit")
                .symbol("\uD83D\uDC07")
                .build());
        iconSet.add(Icon
                .builder()
                //🦇
                .code(89)
                .name("bat")
                .symbol("\uD83E\uDD87")
                .build());
        iconSet.add(Icon
                .builder()
                //🦆
                .code(90)
                .name("duck")
                .symbol("\uD83E\uDD86")
                .build());
        iconSet.add(Icon
                .builder()
                //🦉
                .code(91)
                .name("owl")
                .symbol("\uD83E\uDD89")
                .build());
        iconSet.add(Icon
                .builder()
                //🐦
                .code(92)
                .name("black bird")
                .symbol("\uD83D\uDC26")
                .build());
        iconSet.add(Icon
                .builder()
                //🌹
                .code(93)
                .name("rose")
                .symbol("\uD83C\uDF39")
                .build());
        iconSet.add(Icon
                .builder()
                //🌻
                .code(94)
                .name("sunflower")
                .symbol("\uD83C\uDF3B")
                .build());
        iconSet.add(Icon
                .builder()
                //🌼
                .code(95)
                .name("blossom")
                .symbol("\uD83C\uDF3C")
                .build());
        iconSet.add(Icon
                .builder()
                //🌷
                .code(96)
                .name("tulip")
                .symbol("\uD83C\uDF37")
                .build());
        iconSet.add(Icon
                .builder()
                //🍄
                .code(97)
                .name("brown mushroom")
                .symbol("\uD83C\uDF44")
                .build());
    }
}