# Use root/example as user/password credentials
version: '3.1'

services:
  proxy:
    image: nginx
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - /etc/ssl/private:/etc/ssl/private/
    ports:
      - "443:443"

  api:
    build:
      context: api
    restart: always
    volumes:
      - ./api/build/install/api:/opt/api
      - ./assets:/opt/api/assets
    entrypoint: ./bin/api
    ports:
      - "8080:8080"

  client:
    build:
      context: client
    restart: always
    volumes:
      - ./client/public:/opt/client/public
      - ./client/src:/opt/client/src
    entrypoint: npm start
    ports:
      - "3000:3000"