# Use root/example as user/password credentials
version: '3.1'

services:
  web:
    image: nginx
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d/
      - ./etc/ssl/private:/etc/ssl/private/
    ports:
      - "80:443"